#!/usr/bin/env python3
"""
Language configuration for Deep Research reports.

Shared template for all Latin-script languages, per-language overrides
only specify the translated strings. `get_lang_config(lang)` returns
the merged config.
"""

CHINESE_NUMERALS = ['一', '二', '三', '四', '五', '六', '七', '八', '九', '十',
                    '十一', '十二', '十三', '十四', '十五']

# ── Shared structural elements (not language-specific) ──

_LATIN_CHAPTER = lambda n, title: f"## {n}. {title}"
_LATIN_PREFIX = lambda n: f"{n}."
_LATIN_TOC = lambda prefix, title, anchor: f"- [{prefix} {title}](#{anchor})"

_ZH_CHAPTER = lambda n, title: f"## {CHINESE_NUMERALS[n-1]}、{title}"
_ZH_PREFIX = lambda n: CHINESE_NUMERALS[n-1] + "、"
_ZH_TOC = lambda prefix, title, anchor: f"- [{prefix}{title}](#{anchor})"

# Base template for all 18 non-zh languages
_BASE_LATIN = {
    "sep": " · ",
    "field_sep": ": ",
    "minute_unit": "min",
    "chapter_heading": _LATIN_CHAPTER,
    "toc_prefix": _LATIN_PREFIX,
    "toc_line": _LATIN_TOC,
    "promo_line": "*Generated by [deep-research](https://github.com/hoolulu/deep-research) · One command. Ten minutes. Deep professional reports.*",
    "check": {
        "ch_number_pattern": r'^## \d+\.',
        "ch_has_number_check": True,
    }
}

_BASE_ZH = {
    "sep": " · ",
    "field_sep": "：",
    "minute_unit": "分钟",
    "chapter_heading": _ZH_CHAPTER,
    "toc_prefix": _ZH_PREFIX,
    "toc_line": _ZH_TOC,
    "promo_line": "*本报告由 [deep-research](https://github.com/hoolulu/deep-research) 自动生成 · 一个命令，十分钟，一份深度专业报告*",
    "check": {
        "ch_number_pattern": r'^## ([' + ''.join(CHINESE_NUMERALS) + r']+)、',
        "ch_has_number_check": False,
    }
}

# ── Per-language translated strings only ──
# Each entry specifies only what's different from the base template.
# The fields are: metadata_fields, metadata_label, references_label,
# refs_prefix, refs_count_format, toc_heading, disclaimer_title,
# disclaimer_text, confidence_heading, verdict_labels, report_generated,
# check:{metadata_pattern, references_pattern, tail_refs, tail_disclaimer, tail_confidence}

_LANG = {

"zh": {
    "metadata_fields": ["总字数", "阅读时间", "数据截至", "生成时间", "调研模式", "Skill版本"],
    "metadata_label": "**元数据**：",
    "references_label": "**参考来源**：",
    "refs_prefix": "## 参考来源",
    "refs_count_format": "共引用 {count} 个来源",
    "toc_heading": "## 目录",
    "disclaimer_title": "## 免责声明",
    "disclaimer_text": "本报告基于公开数据整理，不构成投资建议。部分存疑数据已标明，请自行谨慎判断。",
    "confidence_heading": "## 可信评估",
    "verdict_labels": {"reliable": "结论可靠", "moderate": "基本可信", "caution": "谨慎参考"},
    "report_generated": "*报告生成时间：{time}*",
    "check": {
        "metadata_pattern": r'> \*\*元数据\*\*：',
        "references_pattern": r'> \*\*参考来源\*\*',
        "tail_refs": "## 参考来源",
        "tail_disclaimer": "## 免责声明",
        "tail_confidence": "## 可信评估",
    }
},

"en": {
    "metadata_fields": ["Word Count", "Reading Time", "Data Until", "Generated", "Mode", "Skill Version"],
    "metadata_label": "**Metadata**:",
    "references_label": "**References**:",
    "refs_prefix": "## References",
    "refs_count_format": "Total {count} sources",
    "toc_heading": "## Table of Contents",
    "disclaimer_title": "## Disclaimer",
    "disclaimer_text": "This report is compiled from publicly available data and does not constitute investment advice. Some data points are marked as questionable — please exercise your own judgment.",
    "confidence_heading": "## Confidence Assessment",
    "verdict_labels": {"reliable": "Reliable", "moderate": "Moderate", "caution": "Caution"},
    "report_generated": "*Report generated: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadata\*\*:',
        "references_pattern": r'> \*\*References\*\*',
        "tail_refs": "## References",
        "tail_disclaimer": "## Disclaimer",
        "tail_confidence": "## Confidence Assessment",
    }
},

"ja": {
    "metadata_fields": ["文字数", "読了時間", "データ期限", "生成時間", "モード", "Skillバージョン"],
    "metadata_label": "**メタデータ**:",
    "references_label": "**参照元**:",
    "refs_prefix": "## 参照元",
    "refs_count_format": "合計 {count} 件の出典",
    "toc_heading": "## 目次",
    "disclaimer_title": "## 免責事項",
    "disclaimer_text": "本レポートは公開データに基づき作成されたものであり、投資助言を構成するものではありません。疑わしいデータには注釈を付しています。",
    "confidence_heading": "## 信頼性評価",
    "verdict_labels": {"reliable": "信頼できる", "moderate": "ほぼ信頼", "caution": "注意"},
    "report_generated": "*生成時間：{time}*",
    "check": {
        "metadata_pattern": r'> \*\*メタデータ\*\*:',
        "references_pattern": r'> \*\*参照元\*\*',
        "tail_refs": "## 参照元",
        "tail_disclaimer": "## 免責事項",
        "tail_confidence": "## 信頼性評価",
    }
},

"ko": {
    "metadata_fields": ["글자 수", "읽는 시간", "데이터 기준일", "생성 시간", "모드", "Skill 버전"],
    "metadata_label": "**메타데이터**:",
    "references_label": "**참고 자료**:",
    "refs_prefix": "## 참고 자료",
    "refs_count_format": "총 {count}개 출처",
    "toc_heading": "## 목차",
    "disclaimer_title": "## 면책 조항",
    "disclaimer_text": "본 보고서는 공개 데이터를 기반으로 작성되었으며 투자 조언을 구성하지 않습니다. 의심스러운 데이터는 별도 표기되었습니다.",
    "confidence_heading": "## 신뢰도 평가",
    "verdict_labels": {"reliable": "신뢰 가능", "moderate": "대체로 신뢰", "caution": "주의"},
    "report_generated": "*생성 시간：{time}*",
    "check": {
        "metadata_pattern": r'> \*\*메타데이터\*\*:',
        "references_pattern": r'> \*\*참고 자료\*\*',
        "tail_refs": "## 참고 자료",
        "tail_disclaimer": "## 면책 조항",
        "tail_confidence": "## 신뢰도 평가",
    }
},

# ── Latin-script languages (en/es/fr/de/pt/it/nl/sv) ──
# All use _BASE_LATIN for structural fields; only translated strings below.

"es": {
    "metadata_fields": ["Recuento de palabras", "Tiempo de lectura", "Datos hasta", "Generado", "Modo", "Versión Skill"],
    "metadata_label": "**Metadatos**:",
    "references_label": "**Referencias**:",
    "refs_prefix": "## Referencias",
    "refs_count_format": "Total {count} fuentes",
    "toc_heading": "## Índice",
    "disclaimer_title": "## Descargo de responsabilidad",
    "disclaimer_text": "Este informe se elabora a partir de datos públicos y no constituye asesoramiento de inversión. Algunos datos dudosos están señalados.",
    "confidence_heading": "## Evaluación de Confianza",
    "verdict_labels": {"reliable": "Fiable", "moderate": "Moderado", "caution": "Precaución"},
    "report_generated": "*Informe generado: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadatos\*\*:',
        "references_pattern": r'> \*\*Referencias\*\*',
        "tail_refs": "## Referencias",
        "tail_disclaimer": "## Descargo de responsabilidad",
        "tail_confidence": "## Evaluación de Confianza",
    }
},

"fr": {
    "metadata_fields": ["Nombre de mots", "Temps de lecture", "Données jusqu'au", "Généré le", "Mode", "Version Skill"],
    "metadata_label": "**Métadonnées**:",
    "references_label": "**Références**:",
    "refs_prefix": "## Références",
    "refs_count_format": "Total {count} sources",
    "toc_heading": "## Table des matières",
    "disclaimer_title": "## Avertissement",
    "disclaimer_text": "Ce rapport est basé sur des données publiques et ne constitue pas un conseil en investissement. Certaines données douteuses sont signalées.",
    "confidence_heading": "## Évaluation de Confiance",
    "verdict_labels": {"reliable": "Fiable", "moderate": "Modéré", "caution": "Prudence"},
    "report_generated": "*Rapport généré : {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Métadonnées\*\*:',
        "references_pattern": r'> \*\*Références\*\*',
        "tail_refs": "## Références",
        "tail_disclaimer": "## Avertissement",
        "tail_confidence": "## Évaluation de Confiance",
    }
},

"de": {
    "metadata_fields": ["Wortanzahl", "Lesezeit", "Daten bis", "Erstellt", "Modus", "Skill-Version"],
    "metadata_label": "**Metadaten**:",
    "references_label": "**Quellen**:",
    "refs_prefix": "## Quellen",
    "refs_count_format": lambda count: f"Insgesamt {count} Quelle" if count == 1 else f"Insgesamt {count} Quellen",
    "toc_heading": "## Inhaltsverzeichnis",
    "disclaimer_title": "## Haftungsausschluss",
    "disclaimer_text": "Dieser Bericht basiert auf öffentlich zugänglichen Daten und stellt keine Anlageberatung dar. Zweifelhafte Daten sind gekennzeichnet.",
    "confidence_heading": "## Vertrauensbewertung",
    "verdict_labels": {"reliable": "Zuverlässig", "moderate": "Mäßig", "caution": "Vorsicht"},
    "report_generated": "*Bericht erstellt: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadaten\*\*:',
        "references_pattern": r'> \*\*Quellen\*\*',
        "tail_refs": "## Quellen",
        "tail_disclaimer": "## Haftungsausschluss",
        "tail_confidence": "## Vertrauensbewertung",
    }
},

"pt": {
    "metadata_fields": ["Contagem de palavras", "Tempo de leitura", "Dados até", "Gerado em", "Modo", "Versão Skill"],
    "metadata_label": "**Metadados**:",
    "references_label": "**Referências**:",
    "refs_prefix": "## Referências",
    "refs_count_format": "Total de {count} fontes",
    "toc_heading": "## Índice",
    "disclaimer_title": "## Isenção de responsabilidade",
    "disclaimer_text": "Este relatório é baseado em dados públicos e não constitui aconselhamento de investimento. Dados duvidosos estão sinalizados.",
    "confidence_heading": "## Avaliação de Confiança",
    "verdict_labels": {"reliable": "Confiável", "moderate": "Moderado", "caution": "Cautela"},
    "report_generated": "*Relatório gerado: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadados\*\*:',
        "references_pattern": r'> \*\*Referências\*\*',
        "tail_refs": "## Referências",
        "tail_disclaimer": "## Isenção de responsabilidade",
        "tail_confidence": "## Avaliação de Confiança",
    }
},

"it": {
    "metadata_fields": ["Conteggio parole", "Tempo di lettura", "Dati fino al", "Generato", "Modalità", "Versione Skill"],
    "metadata_label": "**Metadati**:",
    "references_label": "**Fonti**:",
    "refs_prefix": "## Fonti",
    "refs_count_format": "Totale {count} fonti",
    "toc_heading": "## Indice",
    "disclaimer_title": "## Dichiarazione di non responsabilità",
    "disclaimer_text": "Il presente rapporto si basa su dati pubblici e non costituisce consulenza in materia di investimenti. I dati dubbi sono contrassegnati.",
    "confidence_heading": "## Valutazione di Affidabilità",
    "verdict_labels": {"reliable": "Affidabile", "moderate": "Moderato", "caution": "Attenzione"},
    "report_generated": "*Rapporto generato: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadati\*\*:',
        "references_pattern": r'> \*\*Fonti\*\*',
        "tail_refs": "## Fonti",
        "tail_disclaimer": "## Dichiarazione di non responsabilità",
        "tail_confidence": "## Valutazione di Affidabilità",
    }
},

"nl": {
    "metadata_fields": ["Woordenaantal", "Leestijd", "Gegevens tot", "Gegenereerd", "Modus", "Skill-versie"],
    "metadata_label": "**Metadata**:",
    "references_label": "**Bronnen**:",
    "refs_prefix": "## Bronnen",
    "refs_count_format": "Totaal {count} bronnen",
    "toc_heading": "## Inhoudsopgave",
    "disclaimer_title": "## Vrijwaring",
    "disclaimer_text": "Dit rapport is gebaseerd op openbare gegevens en vormt geen beleggingsadvies. Twijfelachtige gegevens zijn gemarkeerd.",
    "confidence_heading": "## Betrouwbaarheidsbeoordeling",
    "verdict_labels": {"reliable": "Betrouwbaar", "moderate": "Matig", "caution": "Voorzichtig"},
    "report_generated": "*Rapport gegenereerd: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadata\*\*:',
        "references_pattern": r'> \*\*Bronnen\*\*',
        "tail_refs": "## Bronnen",
        "tail_disclaimer": "## Vrijwaring",
        "tail_confidence": "## Betrouwbaarheidsbeoordeling",
    }
},

"sv": {
    "metadata_fields": ["Ordantal", "Lästid", "Data till", "Skapad", "Läge", "Skill-version"],
    "metadata_label": "**Metadata**:",
    "references_label": "**Källor**:",
    "refs_prefix": "## Källor",
    "refs_count_format": "Totalt {count} källor",
    "toc_heading": "## Innehållsförteckning",
    "disclaimer_title": "## Ansvarsfriskrivning",
    "disclaimer_text": "Denna rapport är baserad på offentligt tillgängliga data och utgör inte investeringsrådgivning. Tveksamma data är markerade.",
    "confidence_heading": "## Förtroendebedömning",
    "verdict_labels": {"reliable": "Tillförlitlig", "moderate": "Måttlig", "caution": "Försiktighet"},
    "report_generated": "*Rapport genererad: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadata\*\*:',
        "references_pattern": r'> \*\*Källor\*\*',
        "tail_refs": "## Källor",
        "tail_disclaimer": "## Ansvarsfriskrivning",
        "tail_confidence": "## Förtroendebedömning",
    }
},

"ru": {
    "metadata_fields": ["Количество слов", "Время чтения", "Данные до", "Создано", "Режим", "Версия Skill"],
    "metadata_label": "**Метаданные**:",
    "references_label": "**Источники**:",
    "refs_prefix": "## Источники",
    "refs_count_format": "Всего {count} источников",
    "toc_heading": "## Содержание",
    "disclaimer_title": "## Отказ от ответственности",
    "disclaimer_text": "Данный отчет основан на общедоступных данных и не является инвестиционной рекомендацией. Сомнительные данные отмечены.",
    "confidence_heading": "## Оценка достоверности",
    "verdict_labels": {"reliable": "Надёжно", "moderate": "Умеренно", "caution": "Осторожно"},
    "report_generated": "*Отчет создан: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Метаданные\*\*:',
        "references_pattern": r'> \*\*Источники\*\*',
        "tail_refs": "## Источники",
        "tail_disclaimer": "## Отказ от ответственности",
        "tail_confidence": "## Оценка достоверности",
    }
},

# ── RTL / non-Latin script languages ──

"ar": {
    "metadata_fields": ["عدد الكلمات", "وقت القراءة", "البيانات حتى", "تاريخ الإنشاء", "الوضع", "إصدار المهارة"],
    "metadata_label": "**البيانات الوصفية**:",
    "references_label": "**المصادر**:",
    "refs_prefix": "## المصادر",
    "refs_count_format": "إجمالي {count} مصدرًا",
    "toc_heading": "## المحتويات",
    "disclaimer_title": "## إخلاء المسؤولية",
    "disclaimer_text": "يعتمد هذا التقرير على بيانات متاحة للعموم ولا يشكل نصيحة استثمارية. تم وضع علامات على البيانات المشكوك فيها.",
    "confidence_heading": "## تقييم الثقة",
    "verdict_labels": {"reliable": "موثوق", "moderate": "معتدل", "caution": "حذر"},
    "report_generated": "*تاريخ إنشاء التقرير: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*البيانات الوصفية\*\*:',
        "references_pattern": r'> \*\*المصادر\*\*',
        "tail_refs": "## المصادر",
        "tail_disclaimer": "## إخلاء المسؤولية",
        "tail_confidence": "## تقييم الثقة",
    }
},

"hi": {
    "metadata_fields": ["शब्द गणना", "पढ़ने का समय", "डेटा तक", "निर्माण समय", "मोड", "कौशल संस्करण"],
    "metadata_label": "**मेटाडेटा**:",
    "references_label": "**स्रोत**:",
    "refs_prefix": "## स्रोत",
    "refs_count_format": "कुल {count} स्रोत",
    "toc_heading": "## विषय सूची",
    "disclaimer_title": "## अस्वीकरण",
    "disclaimer_text": "यह रिपोर्ट सार्वजनिक डेटा पर आधारित है और निवेश सलाह का गठन नहीं करती है। संदिग्ध डेटा को चिह्नित किया गया है।",
    "confidence_heading": "## विश्वसनीयता मूल्यांकन",
    "verdict_labels": {"reliable": "विश्वसनीय", "moderate": "मध्यम", "caution": "सावधान"},
    "report_generated": "*रिपोर्ट निर्माण समय: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*मेटाडेटा\*\*:',
        "references_pattern": r'> \*\*स्रोत\*\*',
        "tail_refs": "## स्रोत",
        "tail_disclaimer": "## अस्वीकरण",
        "tail_confidence": "## विश्वसनीयता मूल्यांकन",
    }
},

"vi": {
    "metadata_fields": ["Số từ", "Thời gian đọc", "Dữ liệu đến", "Tạo lúc", "Chế độ", "Phiên bản Skill"],
    "metadata_label": "**Siêu dữ liệu**:",
    "references_label": "**Nguồn tham khảo**:",
    "refs_prefix": "## Nguồn tham khảo",
    "refs_count_format": "Tổng số {count} nguồn",
    "toc_heading": "## Mục lục",
    "disclaimer_title": "## Tuyên bố miễn trách",
    "disclaimer_text": "Báo cáo này được tổng hợp từ dữ liệu công khai và không cấu thành lời khuyên đầu tư. Dữ liệu nghi ngờ đã được đánh dấu.",
    "confidence_heading": "## Đánh giá độ tin cậy",
    "verdict_labels": {"reliable": "Đáng tin cậy", "moderate": "Trung bình", "caution": "Thận trọng"},
    "report_generated": "*Báo cáo tạo lúc: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Siêu dữ liệu\*\*:',
        "references_pattern": r'> \*\*Nguồn tham khảo\*\*',
        "tail_refs": "## Nguồn tham khảo",
        "tail_disclaimer": "## Tuyên bố miễn trách",
        "tail_confidence": "## Đánh giá độ tin cậy",
    }
},

"id": {
    "metadata_fields": ["Jumlah kata", "Waktu baca", "Data hingga", "Dibuat", "Mode", "Versi Skill"],
    "metadata_label": "**Metadata**:",
    "references_label": "**Referensi**:",
    "refs_prefix": "## Referensi",
    "refs_count_format": "Total {count} sumber",
    "toc_heading": "## Daftar Isi",
    "disclaimer_title": "## Penyangkalan",
    "disclaimer_text": "Laporan ini disusun berdasarkan data publik dan tidak merupakan saran investasi. Data yang meragukan telah ditandai.",
    "confidence_heading": "## Penilaian Kepercayaan",
    "verdict_labels": {"reliable": "Terpercaya", "moderate": "Sedang", "caution": "Hati-hati"},
    "report_generated": "*Laporan dibuat: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadata\*\*:',
        "references_pattern": r'> \*\*Referensi\*\*',
        "tail_refs": "## Referensi",
        "tail_disclaimer": "## Penyangkalan",
        "tail_confidence": "## Penilaian Kepercayaan",
    }
},

"th": {
    "metadata_fields": ["จำนวนคำ", "เวลาอ่าน", "ข้อมูลถึง", "สร้างเมื่อ", "โหมด", "เวอร์ชัน Skill"],
    "metadata_label": "**ข้อมูลเมตา**:",
    "references_label": "**แหล่งอ้างอิง**:",
    "refs_prefix": "## แหล่งอ้างอิง",
    "refs_count_format": "รวม {count} แหล่งที่มา",
    "toc_heading": "## สารบัญ",
    "disclaimer_title": "## ข้อจำกัดความรับผิดชอบ",
    "disclaimer_text": "รายงานนี้รวบรวมจากข้อมูลสาธารณะและไม่ถือเป็นคำแนะนำด้านการลงทุน ข้อมูลที่น่าสงสัยถูกทำเครื่องหมายไว้",
    "confidence_heading": "## การประเมินความน่าเชื่อถือ",
    "verdict_labels": {"reliable": "เชื่อถือได้", "moderate": "ปานกลาง", "caution": "ระวัง"},
    "report_generated": "*รายงานสร้างเมื่อ: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*ข้อมูลเมตา\*\*:',
        "references_pattern": r'> \*\*แหล่งอ้างอิง\*\*',
        "tail_refs": "## แหล่งอ้างอิง",
        "tail_disclaimer": "## ข้อจำกัดความรับผิดชอบ",
        "tail_confidence": "## การประเมินความน่าเชื่อถือ",
    }
},

"tr": {
    "metadata_fields": ["Kelime sayısı", "Okuma süresi", "Veri tarihine kadar", "Oluşturma zamanı", "Mod", "Skill Sürümü"],
    "metadata_label": "**Meta veri**:",
    "references_label": "**Kaynaklar**:",
    "refs_prefix": "## Kaynaklar",
    "refs_count_format": "Toplam {count} kaynak",
    "toc_heading": "## İçindekiler",
    "disclaimer_title": "## Sorumluluk reddi",
    "disclaimer_text": "Bu rapor kamuya açık verilere dayanmaktadır ve yatırım tavsiyesi niteliği taşımaz. Şüpheli veriler işaretlenmiştir.",
    "confidence_heading": "## Güven Değerlendirmesi",
    "verdict_labels": {"reliable": "Güvenilir", "moderate": "Orta", "caution": "Dikkat"},
    "report_generated": "*Rapor oluşturma zamanı: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Meta veri\*\*:',
        "references_pattern": r'> \*\*Kaynaklar\*\*',
        "tail_refs": "## Kaynaklar",
        "tail_disclaimer": "## Sorumluluk reddi",
        "tail_confidence": "## Güven Değerlendirmesi",
    }
},

"pl": {
    "metadata_fields": ["Liczba słów", "Czas czytania", "Dane do", "Wygenerowano", "Tryb", "Wersja Skill"],
    "metadata_label": "**Metadane**:",
    "references_label": "**Źródła**:",
    "refs_prefix": "## Źródła",
    "refs_count_format": "Łącznie {count} źródeł",
    "toc_heading": "## Spis treści",
    "disclaimer_title": "## Zrzeczenie się odpowiedzialności",
    "disclaimer_text": "Raport został opracowany na podstawie danych publicznych i nie stanowi porady inwestycyjnej. Wątpliwe dane zostały oznaczone.",
    "confidence_heading": "## Ocena Wiarygodności",
    "verdict_labels": {"reliable": "Godny zaufania", "moderate": "Umiarkowany", "caution": "Ostrożność"},
    "report_generated": "*Raport wygenerowano: {time}*",
    "check": {
        "metadata_pattern": r'> \*\*Metadane\*\*:',
        "references_pattern": r'> \*\*Źródła\*\*',
        "tail_refs": "## Źródła",
        "tail_disclaimer": "## Zrzeczenie się odpowiedzialności",
        "tail_confidence": "## Ocena Wiarygodności",
    }
},

}  # end _LANG


# ── Build LANG_CONFIG by merging base template + per-language overrides ──

LANG_CONFIG = {}
for code, overrides in _LANG.items():
    base = dict(_BASE_ZH if code == "zh" else _BASE_LATIN)
    # Merge check dict
    if 'check' in overrides:
        merged_check = dict(base.get('check', {}))
        merged_check.update(overrides.pop('check'))
        overrides['check'] = merged_check
    base.update(overrides)
    LANG_CONFIG[code] = base


def get_lang_config(lang: str) -> dict:
    """Get language config. Falls back to English for unsupported languages."""
    return LANG_CONFIG.get(lang, LANG_CONFIG["en"])
